export {
  DASHBOARD_ACTIVITY_ACTIONS,
  DASHBOARD_MAX_NEEDS_ATTENTION_PREVIEW_LIMIT,
  DASHBOARD_MAX_RECENT_ACTIVITY_LIMIT,
  DASHBOARD_MAX_UPCOMING_HORIZON_DAYS,
  DASHBOARD_MAX_UPCOMING_LIMIT,
  DASHBOARD_NEEDS_ATTENTION_PREVIEW_LIMIT,
  DASHBOARD_RECENT_ACTIVITY_LIMIT,
  DASHBOARD_UPCOMING_HORIZON_DAYS,
  DASHBOARD_UPCOMING_LIMIT,
  PLACEMENT_LABELS,
  dashboardActivitySummaryCode,
  dashboardModuleVisibility,
  deriveCurationStatus,
  isAllowlistedDashboardActivity,
  normalizeCommunicationsDashboardRequest,
  type CommunicationsDashboard,
  type CommunicationsDashboardRequest,
  type DashboardActivityItem,
  type DashboardActivityKind,
  type DashboardCurationSlot,
  type DashboardCurationStatus,
  type DashboardCurrentCurationModule,
  type DashboardNeedsAttentionGroup,
  type DashboardNeedsAttentionGroupKey,
  type DashboardNeedsAttentionModule,
  type DashboardPlacementAssignment,
  type DashboardPlacementEligibility,
  type DashboardPublicationItem,
  type DashboardRecentActivityModule,
  type DashboardUpcomingItem,
  type DashboardUpcomingModule,
  type DashboardModuleVisibility,
  type NormalizedCommunicationsDashboardRequest,
  type PlacementKey,
} from "./dashboard-contracts";
export { getCommunicationsDashboard } from "./dashboard-service";
